// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhatsTheWeatherDatabaseAccess;

#nullable disable

namespace WhatsTheWeather.Migrations
{
    [DbContext(typeof(StatisticsDbContext))]
    [Migration("20220529170925_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WhatsTheWeatherDatabaseAccess.DbModels.LocationVisits", b =>
                {
                    b.Property<int>("LocationVisitsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationVisitsId"), 1L, 1);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VisitsCounter")
                        .HasColumnType("int");

                    b.HasKey("LocationVisitsId");

                    b.ToTable("LocationVisits");
                });
#pragma warning restore 612, 618
        }
    }
}
